### ISSUE TITLE
DiceCTF/2022/knock-knock - randomUUID secret key value

### ISSUE THREAD

**Issue by francesco-scar** [Tzion0/CTF#1]
Hi,

In the writeup DiceCTF/2022/knock-knock you say that

> The calling of `crypto.randomUUID` missing a parenthesis, it actually will always return `undefined`

but testing with 

```js
let a = `secret-${crypto.randomUUID}`
console.log(a);
```

i think that `${crypto.randomUUID}` (without parenthesis) returns the code of the function as text, because the previous code outputs the following text

```
secret-function randomUUID(options) {
  if (options !== undefined)
    validateObject(options, 'options');
  const {
    disableEntropyCache = false,
  } = options || {};

  validateBoolean(disableEntropyCache, 'options.disableEntropyCache');

  return disableEntropyCache ? getUnbufferedUUID() : getBufferedUUID();
}
```

This difference doesn't affect the solution of the challenge, because you actually stored that string in a variable and used it to generate the token, but I think that the detail could be interesting.

Thank you

**Comment by Tzion0** [comment]
Hi,

Thank you for clarifying the detail for me. I noticed that I'm using a lower version of Nodejs instead of recommended version `17.4.0-buster-slim` which will actually return `undefined`, tested using https://www.jdoodle.com/execute-nodejs-online/ (please correct me if i am wrong):

![image](https://user-images.githubusercontent.com/90162069/152780584-9f5200fd-9e02-4dfa-8e99-eeffbdf33539.png)

However, when i change to higher version of Nodejs that near to the recommended version, it will return the text you mentioned:

![image](https://user-images.githubusercontent.com/90162069/152780830-b918ad55-0f61-4388-8fe7-c513d64f7f6f.png)

Although the difference doesn't affect the solution of the challenge but I do really appreciate your help on providing me the correct information. Will fix it ASAP, thank you again !

Warm regards,
Tzion

**Comment by francesco-scar** [comment]
Thanks for the explanation, I can reproduce the same behavior whit the older version you specified.

By the way using a different key you should get different hash (as expected) and testing the following code

```js
let crypto = require('crypto');
let id = 0;

let a = `secret-${crypto.randomUUID}`;

console.log(a);

let r = crypto.createHmac('sha256', a).update(id.toString()).digest('hex');
console.log(r);
```

with version 12.11.1 I get the output

```
secret-undefined
670de7d6dfe9da4fce60cbf52d46a30aeeb00f0bc05908d05ba1efb227e4bd1b
```

which is a wrong token, so maybe you used the right nodejs version during the challenge (just a supposition, but I can't find any other plausible possibility).

Thanks for your work and for answering

Best regards,
Francesco

**Comment by Tzion0** [comment]
Oh ya, you're right, my bad on not verify that while writing the write up. I thought version doesn't matter at that time. Thank you for the information, I'm fixing it. Thanks again !

Regards,
Tzion
